# Generated by Django 4.2.14 on 2024-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oss',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
