# Generated by Django 4.2.14 on 2024-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0002_oss_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oss',
            name='expirationDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
