# Generated by Django 4.2.14 on 2024-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0003_alter_oss_expirationdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oss',
            options={'ordering': ('prettyName',), 'verbose_name': 'Операционные системы', 'verbose_name_plural': 'Операционную систему'},
        ),
        migrations.AlterField(
            model_name='oss',
            name='prettyName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='bitness',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='distroName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='distroVersion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='familyName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='ipAdress',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='kernelVersion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vms',
            name='powerState',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='prettyName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='toolsStatus',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vms',
            name='vmtoolsdescription',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
