# Generated by Django 4.2.14 on 2024-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0004_alter_oss_options_alter_oss_prettyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='resourcePool',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
