# Generated by Django 4.2.14 on 2024-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0005_vms_resourcepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='cms',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
