# Generated by Django 4.2.14 on 2024-12-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0009_systeminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_ports', models.JSONField(default=list, verbose_name='Listen Ports')),
                ('ip_addresses', models.JSONField(default=list, verbose_name='IP Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='NginxDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True, verbose_name='Domain Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.AddField(
            model_name='nginxconfig',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='vmconnectapp.nginxdomain'),
        ),
    ]
