# Generated by Django 4.2.14 on 2025-01-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0010_nginxconfig_nginxdomain_delete_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxconfig',
            name='waf',
            field=models.BooleanField(default=False, verbose_name='WAF'),
        ),
    ]
