# Generated by Django 4.2.14 on 2025-02-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0011_nginxconfig_waf'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxconfig',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
