# Generated by Django 4.2.14 on 2025-03-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmconnectapp', '0012_nginxconfig_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
